version: '2'
services:
  speed-checker-postgres:
    image: drobinson/speed-checker-postgres
    container_name: speed-checker-postgres
    hostname: speed-checker-postgres
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=speed
      - POSTGRES_DB=speed
    volumes:
      - speed-checker-postgres-db-volume:/var/lib/postgresql/data
  speed-checker:
    image: drobinson/speed-checker
    container_name: speed-checker
    depends_on:
      - speed-checker-postgres
  speed-checker-flask:
    image: drobinson/speed-checker-flask
    container_name: speed-checker-flask
    ports:
      - "5000:5000"
    depends_on:
      - speed-checker
      - speed-checker-postgres
volumes:
  speed-checker-postgres-db-volume: